version: '3'
services:
  nextjs-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 80:80