name: Deploy Frontend
on:
  push:
    branches:
      -  main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push - Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: dylanchau/docker-demo:latest
      
      - name: Build and push - Nginx
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: dylanchau/docker-nginx-demo:latest
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: MyApp-dev
          environment_name: MyApp-dev
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-526267381761
          region: ap-southeast-1 
          version_label: ${{ github.sha }}
          deployment_package: docker-compose.yml
